spring.application.name=board

## -- Gemini API -- ##
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}
server.port=8090
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

## -- image upload -- ##
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

