spring:
  datasource:
    url: jdbc:sqlite:./data/app.db?foreign_keys=on
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        show_sql: true
        format_sql: true
